create table if not exists public.resenas (
  id bigint generated by default as identity primary key,
  pelicula_id bigint not null references public.peliculas (id) on delete cascade,
  usuario_id uuid not null references auth.users (id) on delete cascade,
  puntuacion smallint not null check (puntuacion between 1 and 5),
  comentario text check (
    comentario is null or char_length(trim(comentario)) <= 500
  ),
  fecha_creacion timestamptz not null default now(),
  unique (pelicula_id, usuario_id)
);

alter table public.resenas enable row level security;

revoke all on table public.resenas from anon, authenticated;
grant select on table public.resenas to anon, authenticated;
grant insert, update, delete on table public.resenas to authenticated;

drop policy if exists "Las reseñas son visibles para todos" on public.resenas;
create policy "Las reseñas son visibles para todos"
  on public.resenas for select
  to anon, authenticated
  using (true);

drop policy if exists "Cada usuario crea sus propias reseñas" on public.resenas;
create policy "Cada usuario crea sus propias reseñas"
  on public.resenas for insert
  to authenticated
  with check ((select auth.uid()) = usuario_id);

drop policy if exists "Cada usuario modifica sus propias reseñas" on public.resenas;
create policy "Cada usuario modifica sus propias reseñas"
  on public.resenas for update
  to authenticated
  using ((select auth.uid()) = usuario_id)
  with check ((select auth.uid()) = usuario_id);

drop policy if exists "Cada usuario elimina sus propias reseñas" on public.resenas;
create policy "Cada usuario elimina sus propias reseñas"
  on public.resenas for delete
  to authenticated
  using ((select auth.uid()) = usuario_id);

notify pgrst, 'reload schema';