create table if not exists public.peliculas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  imagen text not null,
  sinopsis text not null,
  duracion integer not null check (duracion > 0),
  genero text not null,
  clasificacion_edad integer not null check (clasificacion_edad in (0, 13, 18)),
  fecha_estreno date,
  esta_disponible boolean not null default true
);

create table if not exists public.salas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  filas integer not null check (filas between 1 and 20)
);

create table if not exists public.funciones (
  id bigint generated by default as identity primary key,
  pelicula_id bigint not null references public.peliculas (id),
  sala_id bigint not null references public.salas (id),
  fecha date not null,
  hora time not null,
  precio_entrada numeric(10, 2) not null check (precio_entrada >= 0)
);

alter table public.peliculas enable row level security;
alter table public.salas enable row level security;
alter table public.funciones enable row level security;

grant select on table public.peliculas, public.salas, public.funciones to anon, authenticated;
revoke insert, update, delete on table public.peliculas, public.salas, public.funciones from anon, authenticated;

drop policy if exists "Catalog is readable by everyone" on public.peliculas;
create policy "Catalog is readable by everyone" on public.peliculas
  for select to anon, authenticated using (true);

drop policy if exists "Rooms are readable by everyone" on public.salas;
create policy "Rooms are readable by everyone" on public.salas
  for select to anon, authenticated using (true);

drop policy if exists "Showtimes are readable by everyone" on public.funciones;
create policy "Showtimes are readable by everyone" on public.funciones
  for select to anon, authenticated using (true);

insert into public.peliculas (id, nombre, imagen, sinopsis, duracion, genero, clasificacion_edad, fecha_estreno, esta_disponible)
values
  (1, 'Interestelar', 'assets/images/interestelar.jpg', 'Un grupo de astronautas busca un nuevo hogar para la humanidad.', 169, 'Ciencia ficción', 13, null, true),
  (2, 'El Padrino', 'assets/images/el-padrino.jpg', 'La historia de una poderosa familia dedicada al crimen organizado.', 175, 'Drama', 18, null, false),
  (3, 'El Padrino II', 'assets/images/el-padrino.jpg', 'La historia de una poderosa familia dedicada al crimen organizado.', 175, 'Drama', 18, null, false)
on conflict (id) do nothing;

insert into public.salas (id, nombre, filas)
values (1, 'Sala 1', 20), (2, 'Sala 2', 20)
on conflict (id) do nothing;

insert into public.funciones (id, pelicula_id, sala_id, fecha, hora, precio_entrada)
values
  (1, 1, 1, '2026-09-17', '18:00', 5000),
  (2, 1, 2, '2026-09-17', '20:30', 8000),
  (3, 1, 1, '2026-09-17', '22:45', 8000),
  (4, 2, 2, '2026-09-17', '19:00', 5000)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.peliculas', 'id'), coalesce((select max(id) from public.peliculas), 1));
select setval(pg_get_serial_sequence('public.salas', 'id'), coalesce((select max(id) from public.salas), 1));
select setval(pg_get_serial_sequence('public.funciones', 'id'), coalesce((select max(id) from public.funciones), 1));
