create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  cliente_id uuid references auth.users (id) on delete set null,
  fecha_venta timestamptz not null default now(),
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  precio_final numeric(10, 2) not null check (precio_final >= 0),
  forma_pago smallint not null check (forma_pago in (1, 2, 3, 4, 9)),
  esta_pagado boolean not null default false,
  esta_cancelada boolean not null default false
);

create table if not exists public.entradas (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.ventas (id) on delete cascade,
  funcion_id bigint not null references public.funciones (id),
  fila text not null,
  asiento integer not null check (asiento > 0),
  precio numeric(10, 2) not null check (precio >= 0),
  estado_entrada text not null default 'emitida'
    check (estado_entrada in ('disponible', 'emitida', 'utilizada', 'cancelada'))
);

create unique index if not exists entradas_butaca_emitida_unica
  on public.entradas (funcion_id, fila, asiento)
  where estado_entrada = 'emitida';

alter table public.ventas enable row level security;
alter table public.entradas enable row level security;

revoke all on table public.ventas, public.entradas from anon, authenticated;
grant select on table public.ventas, public.entradas to authenticated;

drop policy if exists "Users can read their own sales" on public.ventas;
create policy "Users can read their own sales" on public.ventas
  for select to authenticated
  using ((select auth.uid()) = cliente_id);

drop policy if exists "Users can read tickets from their own sales" on public.entradas;
create policy "Users can read tickets from their own sales" on public.entradas
  for select to authenticated
  using (
    exists (
      select 1 from public.ventas
      where public.ventas.id = public.entradas.venta_id
        and public.ventas.cliente_id = (select auth.uid())
    )
  );

create or replace function public.confirmar_compra(
  p_funcion_id bigint,
  p_butacas jsonb,
  p_forma_pago smallint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_precio_base numeric(10, 2);
  v_subtotal numeric(10, 2);
  v_venta_id bigint;
  v_entradas jsonb;
begin
  if p_butacas is null or jsonb_typeof(p_butacas) <> 'array' then
    raise exception 'Debe seleccionar al menos una butaca.' using errcode = '22023';
  end if;

  if jsonb_array_length(p_butacas) = 0 then
    raise exception 'Debe seleccionar al menos una butaca.' using errcode = '22023';
  end if;

  if p_forma_pago is null or p_forma_pago not in (1, 2, 3, 4, 9) then
    raise exception 'El medio de pago no es válido.' using errcode = '22023';
  end if;

  select precio_entrada into v_precio_base
  from public.funciones
  where id = p_funcion_id;

  if not found then
    raise exception 'La función no existe.' using errcode = '22023';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_butacas) as b(fila text, asiento integer)
    where b.fila is null
      or b.asiento is null
      or b.fila not in ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J/K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T')
      or b.asiento < 1
      or b.asiento > case when b.fila = 'J/K' then 14 else 28 end
  ) then
    raise exception 'La selección contiene una butaca inválida.' using errcode = '22023';
  end if;

  if exists (
    select b.fila, b.asiento
    from jsonb_to_recordset(p_butacas) as b(fila text, asiento integer)
    group by b.fila, b.asiento
    having count(*) > 1
  ) then
    raise exception 'La selección contiene butacas repetidas.' using errcode = '22023';
  end if;

  select coalesce(sum(
    v_precio_base * case when b.fila in ('R', 'S', 'T') then 1.5 else 1 end
  ), 0)
  into v_subtotal
  from jsonb_to_recordset(p_butacas) as b(fila text, asiento integer);

  insert into public.ventas (cliente_id, subtotal, precio_final, forma_pago, esta_pagado)
  values ((select auth.uid()), v_subtotal, v_subtotal, p_forma_pago, true)
  returning id into v_venta_id;

  with entradas_guardadas as (
    insert into public.entradas (venta_id, funcion_id, fila, asiento, precio, estado_entrada)
    select
      v_venta_id,
      p_funcion_id,
      b.fila,
      b.asiento,
      v_precio_base * case when b.fila in ('R', 'S', 'T') then 1.5 else 1 end,
      'emitida'
    from jsonb_to_recordset(p_butacas) as b(fila text, asiento integer)
    returning id, fila, asiento, precio
  )
  select jsonb_agg(jsonb_build_object(
    'id', id,
    'fila', fila,
    'asiento', asiento,
    'precio', precio
  ) order by id)
  into v_entradas
  from entradas_guardadas;

  return jsonb_build_object(
    'venta_id', v_venta_id,
    'subtotal', v_subtotal,
    'precio_final', v_subtotal,
    'entradas', v_entradas
  );
end;
$$;

create or replace function public.obtener_butacas_ocupadas(p_funcion_id bigint)
returns table (fila text, asiento integer)
language sql
stable
security definer
set search_path = ''
as $$
  select e.fila, e.asiento
  from public.entradas e
  join public.ventas v on v.id = e.venta_id
  where e.funcion_id = p_funcion_id
    and e.estado_entrada = 'emitida'
    and v.esta_pagado
    and not v.esta_cancelada;
$$;

revoke all on function public.confirmar_compra(bigint, jsonb, smallint) from public;
revoke all on function public.obtener_butacas_ocupadas(bigint) from public;
grant execute on function public.confirmar_compra(bigint, jsonb, smallint) to anon, authenticated;
grant execute on function public.obtener_butacas_ocupadas(bigint) to anon, authenticated;

select setval(
  pg_get_serial_sequence('public.ventas', 'id'),
  coalesce((select max(id) from public.ventas), 1),
  exists (select 1 from public.ventas)
);
select setval(
  pg_get_serial_sequence('public.entradas', 'id'),
  coalesce((select max(id) from public.entradas), 1),
  exists (select 1 from public.entradas)
);

notify pgrst, 'reload schema';
